#sources:
#  - name: yossi
#    # opal client should get a token.
#    # 2 apis:
#    #   // Get OPA details
#    #   // Register callback.
#    #   //
#    opa_address: 127.0.0.1:8181
#    opal_client_address: 127.0.0.1:7000
#    jwt: something
#  -
bind: ":8080"

sources:
  - id: local
    url: http://localhost:7000
    token: ""
    advertisedAddress: host.docker.internal:8080

target:
  targetType: launchdarkly
  targetSpec:
    #    endpointUrl: "http://localhost:1234/toggles"
    #    extraHeaders:
    #      shalosh: "sfd"
    launchdarklyToken: "api-5549abd8-5683-4f16-9d2f-e1797b132a02"

toggles:
  - key: "us-feature"
    usersPolicy:
      source: local
      package: "app.rbac"
      rule: "us_users"
    spec:
      name: "US Feature"
      #      description: "very flag"
      projKey: "default"
      environments: [ "production", "test" ]
  - key: "billing-feature"
    usersPolicy:
      source: local
      package: "app.rbac"
      rule: "billing_users"
    spec:
      name: "Billing Feature"
      projKey: "default"
      environments: [ "test" ]
