opa:
  address: 127.0.0.1:8181
  jwt: something

opal:
  address: 127.0.0.1:7002
  jwt: something

togglesTarget:
  targetType: launchdarkly
  ldAddress: 127.0.0.1:1337
  ldJwt: something

toggles:
  - key: us-feature
    usersDocument:
      package: "app.rbac"
      name: "us_users"
  - key: billing-feature
    usersDocument:
      package: "app.rbac"
      name: "billing_users"
